### ISSUE TITLE
TimeSeries View config crash

### ISSUE THREAD

**Issue by delhomer** [Oslandia/QGeoloGIS#49]
I try to use QGeoloGIS on a ready-to-use QGIS project:
```
QGIS3_PROFILE=my_profile make deploy
QGIS3_PROFILE=my_profile qgis my_qgis_project.qgs
```

Then on QGIS, something goes wrong when clicking on the TimeSeries View button. I get the following trace:

```
AttributeError: 'PlotConfig' object has no attribute 'get_dict' 
Traceback (most recent call last):
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/qgis_plugin.py", line 106, in 
    self.view_timeseries.triggered.connect(lambda: self.on_view_plots("timeseries"))
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/qgis_plugin.py", line 143, in on_view_plots
    dialog = MainDialog(self.__dock, plot_type, self.__config, layer, self.iface)
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/main_dialog.py", line 263, in __init__
    self.__update_selected_features()
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/main_dialog.py", line 270, in __update_selected_features
    self.__view.set_features(self.__layer.selectedFeatures())
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/main_dialog.py", line 198, in set_features
    self.update_view()
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/main_dialog.py", line 208, in update_view
    self.__config.get_timeseries())
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/main_dialog.py", line 73, in load_plots
    add_function(data, title, uom, station_name=feature_name, config=cfg)
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/qgeologis/timeseries_view.py", line 309, in add_data_row
    self._update_data_row(data, config)
  File "/home/rdelhome/.local/share/QGIS/QGIS3/profiles/cea/python/plugins/QGeoloGIS/qgeologis/timeseries_view.py", line 331, in _update_data_row
    if config and 'min' in config.get_dict() and config['min'] is not None:
AttributeError: 'PlotConfig' object has no attribute 'get_dict'
```

I got this result with v1.3.0, however no problem with v1.2.0.

**Comment by delhomer** [comment]
After some more tests, it looks like the bug was introduced by ea988cd7d59bfea08e6320f2189a8b32b1ac43f5.
